//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Leaderboard
    {
        [Display(Name = "Leaderboard Id")]
        public int ID { get; set; }

        [Display(Name = "User Id")]
        public int UserId { get; set; }

        [Display(Name = "Score")]
        public Nullable<int> Score { get; set; }

        [Display(Name = "Games Played")]
        public Nullable<int> GamesPlayed { get; set; }
    }
}
